### ISSUE TITLE
Error during buid sitewhere-ios-sdk!

### ISSUE THREAD

**Issue by anhdenday** [sitewhere/sitewhere-ios-sdk#1]
Dear @derekadams ,

I am trying to run the sitewhereexample of ios-sdk but it's getting the error. I already follow the instruction here: https://github.com/sitewhere/sitewhere-ios-sdk
But the error appear as the picture I attached below. 

```
(ld: library not found for -lMBProgressHUD
clang: error: linker command failed with exit code 1 (use -v to see invocation))
```

I am using xcode 7 and ios 9.3, please take a look of it.  

![screen shot 2016-04-01 at 1 09 34 am](https://cloud.githubusercontent.com/assets/6926208/14186005/74c7ae8a-f7a6-11e5-8ec3-b2103bb0cb63.png)

Thanks you so much

**Comment by bickster** [comment]
Looks like the MBProgressHUD library is not part of the project.  I'll look into it and back to you today.

Chris

**Comment by bickster** [comment]
I've added a README to the SiteWhereExample project.  There are instructions on how to build the project.  Let me know if that fixes the issue.

[SiteWhereExample project](https://github.com/sitewhere/sitewhere-ios-sdk/tree/master/SiteWhereExample)

**Comment by anhdenday** [comment]
Thanks you so much for your support @bickster . 
The error occur because I run SiteWhereExample.xcodeproj file but your guide is SiteWhereExample.xcworkspace. I just new to iOS so everything is also new for me!
One more question, When I create new device (add new device) on the dashboard, I declare "Hardware Id" is exactly that is my iphone's UUID but each time I run sitewhereexample on my iphone it will create a new iphone device on the dashboard with "Unassociated Device" and also UUID is fixed is "9420583D-25CE-491B-9948-C2A374B00AFA" but the location data is exactly right (I dont know why cause it's not my iphone's UUID). How can I identify that when I register new device that it is my iphone with my UUID so that in dashboard I can view exactly with my iPhone?
Thanks you so much

**Comment by bickster** [comment]
The example app shouldn't be creating a new "hardware id" every time.  The first time you run the app it generates a random hardware id and then stores the id on your phone.  The next time you run the app it will use the hardware id that is stored.

DEBUGING THE ISSUE
In the SiteWhereSDK open up the DeivceUID.m file.  Put a break point on the first line of this method `- (NSString *)uid` Before the save call check the value of _uid.  Run the app again and check the value of _uid. The values should be the same between runs.  Let me know the results.

Chris

**Comment by anhdenday** [comment]
I just following your instruction, it's worked
Thanks for your help
